<?php

function scratchandwin_menu() {
  $items = array();

 $items['claim-prize'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('scratchandwin_claim_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['check-winner/%'] = array(
    'page callback' => '_check_winner',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'page arguments'   => array(1),
  );

  return $items;
}


function scratchandwin_block_info() {
	$blocks['scratch-block'] = array(
    'info' => t('Custom: Scratch Block'),
  );
   	$blocks['winlose-block'] = array(
    'info' => t('Custom: Win Lose Block'),
  );
  return $blocks;
}


function scratchandwin_block_view($delta='') {
  $block = array();
  $nid = arg(1);
  switch ($delta) {
    case 'scratch-block':
      $block['subject'] = 'Scratch Block';
      //$block['content'] = button_contents($nid);
      $block['content'] = _scratch_block($nid);
      break;
    case 'winlose-block':
      $block['subject'] = 'Win Lose Block';
      //$block['content'] = button_contents($nid);
      $block['content'] = _check_winner_block($nid);
      break;
  }

  return $block;
}

function _scratch_block($nid){
  $path = drupal_get_path('module', 'scratchandwin');
//  drupal_add_js($path.'/scratchandwin.js');


  $node = node_load($nid);
  if($node->field_age){
    $age = (integer)$node->field_age['und'][0]['value'];
  }else{
	$age = 0;
  }

  $imgFront = image_style_url('scratch_image', $node->field_scratcher_images['und'][0]['uri']);
  // if($node->field_temp_images){
  //   	$imgBot = image_style_url('scratch_image', $node->field_temp_images['und'][0]['uri']);
  //   }else{
  // 	$imgBot = '';
  //   }

  $imgBack = _check_winner_image($nid);

  $time = strtotime("-$age year", time());
  $date = date("m/d/Y", $time);
  $array = explode('/',$date);
  $age_ver = '<div id="matchdate"><span id="md-m">'.$array[0].'</span<span id="md-d">'.$array[1].'</span><span id="md-y">'.$array[2].'</span></div>';
  $preloadBG = image_style_url('scratch_image', $node->field_scratcher_images['und'][0]['uri']);
  $canvas = '<div id="preloadResultContainer" class="fixedHeight"></div><div id="scratch-canvas" class="scratch-box" data-front="'.$imgFront.'" data-back="'.$imgBack.'"></div>';
  if($node->field_age_verification['und'][0]['value'] == 1){
	 $preloader = '<div id="loading-text" class="enabled"><div id="preloadScreen"><div id="preloadMsg">';
	 $preloader .= '<h4>You must be '.$age.' to play</h4>';
	 $preloader .= $age_ver;
	 $preloader .=  render(drupal_get_form('scratchandwin_age_form'));
	 $preloader .= '</div></div></div>';


  }else{
	$preloader = '';
  }
  $form = '';
  if($_SESSION['status']){
     $form = render(drupal_get_form('scratchandwin_claim_form')); 
  }else if(($_SESSION['status'] == false) && ($node->field_show_form_on_loose['und'][0]['value'] == 1)){
	$form = render(drupal_get_form('scratchandwin_claim_form')); 
  }
  /* need to randomize these */
  $html = '<div class="scratch-block" class="enabled"><div id="scratch-container">'.$canvas.$preloader.$form.'</div></div>';
  $html = $html.'<div id="nindex" rel="'.$nid.'"></div>';
	return $html;
}

function _check_winner_block($nid){
    $html = "";
    $_SESSION['campaign_id'] = '';
    $node = node_load($nid);
    $winner = false;
    $looser = true;
	//get campaign type
	      $type = $node->field_campaign_type['und'][0]['value'];
	      $current_impression = $node->field_current_impressions['und'][0]['value'] + 1;
	      $max_impression = $node->field_impressions['und'][0]['value'];
	      $winner_num = $node->field_winner_['und'][0]['value'];
	      $win_every = $node->field_win_every['und'][0]['value'];
          /*images*/
          $winText = $node->field_win_text['und'][0]['value'];
          $loseText = $node->field_loose_text['und'][0]['value'];

          $win_count = count($node->field_win_images['und']);
          if ($win_count > 1){
            $win_index = rand(0, $win_count);
          }else{
	        $win_index = 0;
          }
          $lose_count = count($node->field_loose_images['und']);
          if($lose_count > 1){
             $lose_index = rand(0, $lose_count);
          }else{
	         $lose_index = 0;
          }

          $winImg = image_style_url('campaign_node_banner', $node->field_win_images['und'][$win_index]['uri']);
          $loseImg = image_style_url('campaign_node_banner', $node->field_loose_images['und'][$lose_index]['uri']);

            $loose .= "<img src='".$loseImg."' border='0' class='img_lose'/>";
         	$loose .= "<p class='wlMsg'>".$loseText."</p>";


			$win .= "<img src='".$winImg."' border='0' class='img_win'/>";
			$win .= "<p class='wlMsg'>".$winText."</p>";
		    //$win .= "<a id='cta_claim_prize' href='/claim-prize'>Claim Your Prize</a>";






	  if($type == 0){
	        //single winner
	        if($current_impression == $winner_num){
		     $_SESSION['campaign_id'] = $nid;
		     $html .= $win;
		     $winner = true;
		     $looser = false;
	        }else{
		     $html .= $loose;
		     $winner = false;
		     $looser = true;
	        }
	      }else if($type == 1){
	        //win every x impressions
//	        $html .= "win every x impressions";
	          if ($current_impression % $win_every == 0) {
		         $_SESSION['campaign_id'] = $nid;
			     $html .= $win;
			     $winner = true;
			     $looser = false;
			  }else{
				$_SESSION['campaign_id'] = $nid;
                 $html .= $loose;
                 $winner = false;
			     $looser = true;
			}
		  }else if ($type == 2){
		   $winners = explode(",", $node->field_random_winners['und'][0]['value']);

		    if(in_array($current_impression,$winners)){
			   	$_SESSION['campaign_id'] = $nid;
			     $html .= $win;
			     $winner = true;
			     $looser = false;
			}else{
				$_SESSION['campaign_id'] = $nid;
				 $html .= $loose;
                 $winner = false;
			     $looser = true;

			}

	      }

	    $node->field_current_impressions['und'][0]['value'] = $current_impression;

	    if($max_impression == $current_impression){
		 $node->status = 0;
	    }
	    node_save($node);

	//echo $html;
	if($winner){
     $html .= render(drupal_get_form('scratchandwin_claim_form'));
    }else if(($looser) && ($node->field_show_form_on_loose['und'][0]['value'] == 1)){
	 $html .= render(drupal_get_form('scratchandwin_claim_form'));
    }

	return $html;
}


function _check_winner_image($nid){
    $html = "";
    $_SESSION['campaign_id'] = '';
    $_SESSION['status'] = false;
    $node = node_load($nid);
    $winner = false;
    $looser = true;
	//get campaign type
	      $type = $node->field_campaign_type['und'][0]['value'];
	      $current_impression = $node->field_current_impressions['und'][0]['value'] + 1;
	      $max_impression = $node->field_impressions['und'][0]['value'];
	      $winner_num = $node->field_winner_['und'][0]['value'];
	      $win_every = $node->field_win_every['und'][0]['value'];
          /*images*/

          $win_count = count($node->field_win_images['und']);
          if ($win_count > 1){
            $win_index = rand(0, $win_count);
          }else{
	        $win_index = 0;
          }
          $lose_count = count($node->field_loose_images['und']);
          if($lose_count > 1){
             $lose_index = rand(0, $lose_count);
          }else{
	         $lose_index = 0;
          }

          $winImg = image_style_url('campaign_node_banner', $node->field_win_images['und'][$win_index]['uri']);
          $loseImg = image_style_url('campaign_node_banner', $node->field_loose_images['und'][$lose_index]['uri']);



	  if($type == 0){
	        //single winner
	        if($current_impression == $winner_num){
		     $_SESSION['campaign_id'] = $nid;
		     $html .= $winImg;
		     $winner = true;
		     $looser = false;
	        }else{
		     $html .= $loseImg;
		     $winner = false;
		     $looser = true;
	        }
	      }else if($type == 1){
	        //win every x impressions
//	        $html .= "win every x impressions";
	          if ($current_impression % $win_every == 0) {
		         $_SESSION['campaign_id'] = $nid;
			     $html .= $winImg;
			     $winner = true;
			     $looser = false;
			  }else{
				$_SESSION['campaign_id'] = $nid;
                 $html .= $loseImg;
                 $winner = false;
			     $looser = true;
			}
		  }else if ($type == 2){
		   $winners = explode(",", $node->field_random_winners['und'][0]['value']);

		    if(in_array($current_impression,$winners)){
			   	$_SESSION['campaign_id'] = $nid;
			     $html .= $winImg;
			     $winner = true;
			     $looser = false;
			}else{
				$_SESSION['campaign_id'] = $nid;
				 $html .= $loseImg;
                 $winner = false;
			     $looser = true;

			}

	      }

	    $node->field_current_impressions['und'][0]['value'] = $current_impression;

	    if($max_impression == $current_impression){
		 $node->status = 0;
	    }
	    node_save($node);

	//echo $html;
	// if($winner){
	//      $html .= render(drupal_get_form('scratchandwin_claim_form'));
	//     }else if(($looser) && ($node->field_show_form_on_loose['und'][0]['value'] == 1)){
	// 	 $html .= render(drupal_get_form('scratchandwin_claim_form'));
	//     }
    $_SESSION['status'] = $winner;
	return $html;
}




function scratchandwin_claim_form($form, &$form_state) {
	if($_SESSION['campaign_id'] == ''){
			drupal_set_message("You don't have access to this page");
			return;
		}
	$form['node'] = array(
		'#type' => 'hidden',
		'#value' => $_SESSION['campaign_id'],
	);
	$form['name'] = array(
		'#type' => 'textfield',
		'#title' => 'Name',
        '#attributes' =>array('placeholder' => t('your Name')),
	);
	$form['email'] = array(
		'#title' => 'Email',
		'#type' => 'textfield',
        '#attributes' =>array('placeholder' => t('your Email')),
    );
	$form['phone'] = array(
		'#title' => 'Phone',
		'#type' => 'textfield',
        '#attributes' =>array('placeholder' => t('your Phone')),
	);
	$form['club'] = array(
		'#title' => 'Join mClub',
		'#type' => 'checkbox',
	);
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );

	return $form;
}

function scratchandwin_age_form($form, &$form_state) {

	  $years = array("" => "", "00" => 'YY');
	  for ($i = (date("Y")-18); $i >= (date("Y")-100); $i--) {
	    $years[$i] = $i;
	  };
      $montharr = array("" => "", "00" => "MM", "01" => "Jan", "02" => "Feb", "03" => "Mar", "04" => "Apr", "05" => "May", "06" => "Jun", "07" => "Jul", "08" => "Aug", "09" => "Sep", "10" => "Oct", "11" => "Nov", "12" => "Dec");
	  $form['field_dob_month'] = array(
	    '#prefix' => '<div class="user-dob">',
	    '#type' => 'select',
	    '#title' => 'Date of Birth',
	    '#options' => $montharr,
	    '#required' => TRUE,
        '#default_value' => '00',
	    );
	  $days = array("" => "", "00" => "DD");
      for ($i = 1; $i <= 31; $i++) {
	    $days[str_pad($i, 2, "0", STR_PAD_LEFT)] = $i;
	  };
	  $form['field_dob_day'] = array(
	    '#title' => 'Day',
	    '#type' => 'select',
	    '#options' => $days,
        '#default_value' => '00',
	    '#required' => TRUE,
	    );
	  $form['field_dob_year'] = array(
	    '#title' => 'Year',
	    '#type' => 'select',
        '#options' => $years,
	    '#required' => TRUE,
        '#default_value' => '00',
	    '#attributes' => array('autocomplete' => 'off'),
	    '#suffix' => '</div>',
	    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );

	return $form;
}

function sw_ajax_age_verify(){


	echo "HI";
}


function scratchandwin_claim_form_submit($form, &$form_state) {

	$nid = $form_state['values']['node'];
	print $nid;
	print "<br>HERE";
    $_SESSION['campaign_id'] = '';
    drupal_set_message("Thank you! And congratulations again! We will get contact you shortly!");
    drupal_goto('/node/'.$nid);
	return;
}


function _UniqueRandomNumbersWithinRange($min, $max, $quantity) {
    $numbers = range($min, $max);
    shuffle($numbers);
    return array_slice($numbers, 0, $quantity);

    //print_r( UniqueRandomNumbersWithinRange(0,25,5) );
}
function scratchandwin_node_presave($node) {
    if ($node->type == 'scratch_campaign'){
			if(($node->field_campaign_type['und'][0]['value'] == 2) && ($node->field_random_winners['und'][0]['value'] == '')){
				$winners = _UniqueRandomNumbersWithinRange(0, $node->field_impressions['und'][0]['value'], $node->field_number_of_random_winners['und'][0]['value']);
				$node->field_random_winners['und'][0]['value'] = implode(",", $winners);
			}

    }

}
